// Create a new Post and sending in params usuarioID
POST http://localhost:3000/api/posts/64468df2500199690a205804 HTTP/1.1
content-type: application/json

{
  "origen": "Centro",
  "destino": "Facu",
  "horario": "14:30",
  "asientosDisponibles": 3,
  "detalles": "Mcal Lopez"
}

// Get all posts
###
GET http://localhost:3000/api/posts