// Create new User
POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json

{
  "name": "Carrera",
  "lastName": "Equivocada",
  "email": "IAE@gmail.com",
  "password": "IAE123",
  "isAdmin": false,
  "phone": "0972224458"
}

// Get Users
###
GET http://localhost:3000/api/users

// Login
###
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "CEP@gmail.com",
  "password": ""
}