// Create new User
POST http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json

{
  "name": "Poli",
  "lastName": "Bicho",
  "email": "polibicho@gmail.com",
  "password": "123fpuna",
  "isAdmin": false,
  "phone": "0971123456"
}

// Get Users
###
GET http://localhost:3000/api/users

// Login
###
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "CEP@gmail.com",
  "password": ""
}